// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Aside: typeof import('./components/layout/Aside/index.tsx')['default']
    BreadCrumb: typeof import('./components/layout/GlobalHeader/components/BreadCrumb/index.tsx')['default']
    Collapse: typeof import('./components/layout/GlobalHeader/components/Collapse/index.tsx')['default']
    DragBar: typeof import('./components/common/DragBar/index.tsx')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    FullScreenCom: typeof import('./components/layout/GlobalHeader/components/FullScreenCom/index.tsx')['default']
    GlobalFooter: typeof import('./components/layout/GlobalFooter/index.tsx')['default']
    GlobalHeader: typeof import('./components/layout/GlobalHeader/index.tsx')['default']
    Loading: typeof import('./components/common/Loading/Loading.tsx')['default']
    MenuTree: typeof import('./components/layout/Aside/components/MenuTree/index.tsx')['default']
    RenderMenuTree: typeof import('./components/layout/Aside/components/MenuTree/renderMenuTree.tsx')['default']
    RenderTreeNode: typeof import('./components/layout/Aside/components/MenuTree/renderTreeNode.tsx')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToggleDark: typeof import('./components/layout/GlobalHeader/components/ToggleDark/index.tsx')['default']
    User: typeof import('./components/layout/GlobalHeader/components/User/index.tsx')['default']
  }
}

export {}
